slam_toolbox:
  ros__parameters:
    # Input/Output
    odom_frame: odom
    map_frame: map
    base_frame: fsds/FSCar
    scan_topic: /scan
    
    # Algorithm
    use_scan_matching: true
    use_scan_bagging: false
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    
    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    
    # Loop closure
    loop_search_max_linear_radius: 3.0
    loop_search_max_angular_distance: 1.57
    
    # Performance
    enable_interactive_mode: true
    synchronize_scans: true
    
    # Position priors
    use_tf_scan_transform_as_initial_guess: true
    transform_publish_period: 0.02
